<a href="https://colab.research.google.com/github/amisaid/ml_zoomcamp23/blob/main/mlzoomcamp_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Installing packages
!pip install NumPy
!pip install Pandas
!pip install Matplotlib
!pip install Seaborn

In [22]:
# Importing packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

### Question 1
What's the version of the Pandas that you installed?  
You can get the version information using the `__version__` field:

In [7]:
pd.__version__

'1.5.3'

### Getting the data

For this homework, we'll use the California Housing Prices dataset. Download it from [here](https://colab.research.google.com/drive/1XP7EYQVSiOZz62osZKAx-3AMKVqiAUp0#scrollTo=VeFSHHyanhpX&line=3&uniqifier=1).

In [9]:
# Getting the data from wget
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-19 08:49:47--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.06s   

2023-09-19 08:49:47 (23.5 MB/s) - ‘housing.csv’ saved [1423529/1423529]



### Question 2

Read the data with pandas.  
How many columns are in the dataset?
* 10
* 6560
* 10989
* 20640

In [11]:
# Reading the dataframe
dataset = pd.read_csv('housing.csv')

In [61]:
dataset.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [17]:
# Count of columns
len(dataset.columns)

10

## Question 3
Which columns in the dataset have missing values?
* `total_rooms`
* `total_bedrooms`
* both of the above
* no empty columns in the dataset

In [27]:
# Count of null values in each column
dataset.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Question 4
How many unique values does the ocean_proximity column have?
* 3
* 5
* 7
* 9

In [40]:
# Count of unique values
len(dataset['ocean_proximity'].unique())

5

### Question 5
What's the average value of the `median_house_value` for the houses located near the bay?
* 49433
* 124805
* 259212
* 380440

In [42]:
# average value of median_house_value
dataset['median_house_value'].mean()

206855.81690891474

### Question 6
1. Calculate the average of `total_bedrooms` column in the dataset.
2. Use the fillna method to fill the missing values in `total_bedrooms` with the mean value from the previous step.
3. Now, calculate the average of `total_bedrooms` again.
4. Has it changed?
Has it changed?

Hint: take into account only 3 digits after the decimal point.

* Yes
* No

In [54]:
# 6.1. Average of total_bedrooms column in the dataset
mean = dataset['total_bedrooms'].mean()
mean

537.8705525375618

In [48]:
print('max is ', dataset['total_bedrooms'].max(),',' ,'min is ', dataset['total_bedrooms'].min(),',' , 'med is ', dataset['total_bedrooms'].median(),',' , 'mean is ', dataset['total_bedrooms'].mean())

max is  6445.0 , min is  1.0 , med is  435.0 , mean is  537.8705525375618


In [55]:
# 6.2. fillna method to fill the missing values in total_bedrooms with the mean value from the previous step
dataset['total_bedrooms'].fillna(mean)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [60]:
# 6.3. Calculate the average of total_bedrooms again with filled na
mean2 = dataset['total_bedrooms'].mean()
mean2

537.8705525375618

In [59]:
# 6.4.Has it changed?
mean == mean2

True

### Question 7
1. Select all the options located on islands.
2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array y with values `[950, 1300, 800, 1000, 1300]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the value of the last element of `w`?
**Note:** You just implemented linear regression. We'll talk about it in the next lesson.

* -1.4812
* 0.001
* 5.6992
* 23.1233

In [66]:
dataset['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [72]:
# 7.1 Select all the options located on islands.
island_dataset= dataset[
    (dataset['ocean_proximity'] == 'ISLAND')
]

In [73]:
# 7.2 Select only columns housing_median_age, total_rooms, total_bedrooms.
island_dataset = island_dataset[['housing_median_age', 'total_rooms', 'total_bedrooms']]
island_dataset

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [75]:
# 7.3 Get the underlying NumPy array. Let's call it X.
X = pd.DataFrame(island_dataset).to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [76]:
# 7.4 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = np.matmul(X.transpose(), X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [96]:
# 7.5 Compute the inverse of XTX.
inv_XTX = (np.linalg.inv(XTX))
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [77]:
# 7.6 Create an array y with values [950, 1300, 800, 1000, 1300].
y = ([950, 1300, 800, 1000, 1300])
y

[950, 1300, 800, 1000, 1300]

In [95]:
# 7.7 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.matmul(np.matmul(inv_XTX, X.transpose()),y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [97]:
# 7.8 What's the value of the last element of w?
w[-1]

5.699229455065586